### PR TITLE
Add linux-armv7l-musl

### PR DESCRIPTION
**Pull request by alexojegu**
This PR add a docker images:

 - linux-armv7-musl: armv7 image with musl as libc

### CODE REVIEW

**Comment by alexojegu** [comment]
It is based on "dockcross/linux-armv7l-musl" I have named the image as "linux-armv7-musl" if it seems more appropriate you could change the name to "linux-armv7l-musl".

The same in the Dockerfile, I have used:
```
ENV PREBUILD_ARCH arm
ENV PREBUILD_ARMV 7
```

But if it is more appropriate I can use (I'm not sure if this would work):
```
ENV PREBUILD_ARCH arm
ENV PREBUILD_ARMV 7l
```

**Comment by vweevers** [comment]
I assume dockcross had a reason for using `arm7l` in this image name (unlike others like `dockcross/linux-armv7` - we just copied those names). Any guesses as to why? I don't know what the L represents or why it's significant for one image and not others.

**Comment by alexojegu** [comment]
I changed the name of everything from `linux-armv7-musl` to `linux-armv7l-musl` but kept the version as 7, if you want I can also change it to 7l.

**Comment by alexojegu** [comment]
Excuse me @vweevers, I don't know if I understood you correctly before. Are you waiting for me to modify "PREBUILD_ARMV" or just for you to get time?

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
> just for you to get time?

just that :)

**Comment by vweevers** [comment]
[2.2.0](https://github.com/prebuild/docker-images/releases/tag/v2.2.0)

**Pull request merged**
